import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "@/componentes/Header";
import GlobalStyles from "@/style/global";
import Providers from "@/app/providers";
import StyledComponentsRegistry from "@/app/registry";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Cadastro",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={inter.className}
      style={{
        background: "#505A5B",
        display: "flex",
        justifyContent:"center",
        alignItems:"center",
      }}
      >
        <StyledComponentsRegistry>
          <Providers>
          <GlobalStyles />
          {children}
          </Providers>
        </StyledComponentsRegistry>
        </body>

    </html>
  );
}