import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "@/componentes/Header";
import StyledComponentsRegistry from "../registry";
import Providers from "../providers";
import GlobalStyles from "@/style/global";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <ToastContainer
          position="top-center"
          theme="colored"
          autoClose={8000}
          hideProgressBar
        />
        <StyledComponentsRegistry>
          <Providers>
          <GlobalStyles />
          <Header />
          {children}
          </Providers>
        </StyledComponentsRegistry>
        </body>

    </html>
  );
}