import type { Metadata } from "next";
import { Inter } from "next/font/google";
import GlobalStyles from "@/style/global";
import Providers from "@/app/providers";
import StyledComponentsRegistry from "@/app/registry";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Login",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={inter.className}
      style={{
        background: "#505A5B"
      }}
      >
        <ToastContainer
          position="top-center"
          theme="colored"
          autoClose={8000}
          hideProgressBar
        />
        <StyledComponentsRegistry>
          <Providers>
          <GlobalStyles />
          {children}
          </Providers>
        </StyledComponentsRegistry>
        </body>

    </html>
  );
}